apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: configuration-policies
placementBindingDefaults:
  name: all-cluster-placement
policyDefaults:
  namespace: policies
  consolidateManifests: false
policies:
#  - name: operator-configuration
#    description: |
#      This policy ensures that the operators in manifests/operators are deployed to ALL clusters (global clusterset).
#      Currently it deploys the following operators:
#      * web-terminal redhat operator
#    manifests:
#      - path: manifests/operators
#        pruneObjectBehavior: DeleteIfCreated
#        remediationAction: enforce
  - name: console-banner
    description: |
      This policy ensures that a console banner is present
    manifests:
      - path: manifests/console-banner
        pruneObjectBehavior: DeleteIfCreated
        remediationAction: enforce
  - name: migrate-workloads-to-infra-nodes
    description: |
      This policy ensures that the following components are configured to deploy on infrastructure nodes:
      * Monitoring
      * Default Router
      For further information consult:
        https://docs.openshift.com/container-platform/4.14/machine_management/creating-infrastructure-machinesets.html#moving-resources-to-infrastructure-machinesets
    manifests:
      - path: manifests/infrastructure-nodes
        pruneObjectBehavior: None
        remediationAction: enforce
    placement:
      placementPath: placements/non-hub-placement.yaml
